import type { ThemeDefinition } from "./types";

export const DEFAULT_THEME_ID = "default";

export const DEFAULT_THEME: ThemeDefinition = {
  id: DEFAULT_THEME_ID,
  name: "Default",
  description: "The built-in Ryco light & dark palette.",
  builtIn: true,
  light: {
    radius: "0.625rem",
    background: "var(--color-white)",
    "app-chrome-background": "var(--background)",
    foreground: "var(--color-neutral-800)",
    card: "var(--color-white)",
    "card-foreground": "var(--color-neutral-800)",
    popover: "var(--color-white)",
    "popover-foreground": "var(--color-neutral-800)",
    primary: "oklch(0.488 0.217 264)",
    "primary-foreground": "var(--color-white)",
    secondary: "--alpha(var(--color-black) / 4%)",
    "secondary-foreground": "var(--color-neutral-800)",
    muted: "--alpha(var(--color-black) / 4%)",
    "muted-foreground": "color-mix(in srgb, var(--color-neutral-500) 90%, var(--color-black))",
    accent: "--alpha(var(--color-black) / 4%)",
    "accent-foreground": "var(--color-neutral-800)",
    destructive: "var(--color-red-500)",
    "destructive-foreground": "var(--color-red-700)",
    border: "--alpha(var(--color-black) / 8%)",
    input: "--alpha(var(--color-black) / 10%)",
    ring: "oklch(0.488 0.217 264)",
    info: "var(--color-blue-500)",
    "info-foreground": "var(--color-blue-700)",
    success: "var(--color-emerald-500)",
    "success-foreground": "var(--color-emerald-700)",
    warning: "var(--color-amber-500)",
    "warning-foreground": "var(--color-amber-700)",
    "scrollbar-thumb": "rgba(0, 0, 0, 0.15)",
    "scrollbar-thumb-hover": "rgba(0, 0, 0, 0.25)",
    "scrollbar-thumb-thin": "rgba(0, 0, 0, 0.1)",
    "scrollbar-thumb-thin-hover": "rgba(0, 0, 0, 0.2)",
    "noise-opacity": "0.035",
    "font-family-sans":
      '"DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif',
    "font-family-mono":
      '"SF Mono", "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
    "font-size-base": "16px",
  },
  dark: {
    background: "color-mix(in srgb, var(--color-neutral-950) 95%, var(--color-white))",
    "app-chrome-background": "var(--background)",
    foreground: "var(--color-neutral-100)",
    card: "color-mix(in srgb, var(--background) 98%, var(--color-white))",
    "card-foreground": "var(--color-neutral-100)",
    popover: "color-mix(in srgb, var(--background) 98%, var(--color-white))",
    "popover-foreground": "var(--color-neutral-100)",
    primary: "oklch(0.588 0.217 264)",
    "primary-foreground": "var(--color-white)",
    secondary: "--alpha(var(--color-white) / 4%)",
    "secondary-foreground": "var(--color-neutral-100)",
    muted: "--alpha(var(--color-white) / 4%)",
    "muted-foreground": "color-mix(in srgb, var(--color-neutral-500) 90%, var(--color-white))",
    accent: "--alpha(var(--color-white) / 4%)",
    "accent-foreground": "var(--color-neutral-100)",
    destructive: "color-mix(in srgb, var(--color-red-500) 90%, var(--color-white))",
    "destructive-foreground": "var(--color-red-400)",
    border: "--alpha(var(--color-white) / 6%)",
    input: "--alpha(var(--color-white) / 8%)",
    ring: "oklch(0.588 0.217 264)",
    info: "var(--color-blue-500)",
    "info-foreground": "var(--color-blue-400)",
    success: "var(--color-emerald-500)",
    "success-foreground": "var(--color-emerald-400)",
    warning: "var(--color-amber-500)",
    "warning-foreground": "var(--color-amber-400)",
    "scrollbar-thumb": "rgba(255, 255, 255, 0.1)",
    "scrollbar-thumb-hover": "rgba(255, 255, 255, 0.18)",
    "scrollbar-thumb-thin": "rgba(255, 255, 255, 0.08)",
    "scrollbar-thumb-thin-hover": "rgba(255, 255, 255, 0.15)",
    "font-family-sans":
      '"DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif',
    "font-family-mono":
      '"SF Mono", "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
    "font-size-base": "16px",
  },
};

const SOLARIZED_DARK: ThemeDefinition = {
  id: "solarized-dark",
  name: "Solarized Dark",
  description: "Ethan Schoonover's iconic dark palette with warm beige accents.",
  builtIn: true,
  light: {
    background: "#fdf6e3",
    "app-chrome-background": "#fdf6e3",
    foreground: "#586e75",
    card: "#fdf6e3",
    "card-foreground": "#586e75",
    popover: "#eee8d5",
    "popover-foreground": "#586e75",
    primary: "#268bd2",
    "primary-foreground": "#fdf6e3",
    secondary: "#eee8d5",
    "secondary-foreground": "#586e75",
    muted: "#eee8d5",
    "muted-foreground": "#93a1a1",
    accent: "#eee8d5",
    "accent-foreground": "#586e75",
    destructive: "#dc322f",
    "destructive-foreground": "#fdf6e3",
    border: "rgba(88, 110, 117, 0.18)",
    input: "rgba(88, 110, 117, 0.22)",
    ring: "#268bd2",
    info: "#268bd2",
    "info-foreground": "#268bd2",
    success: "#859900",
    "success-foreground": "#859900",
    warning: "#b58900",
    "warning-foreground": "#b58900",
    "scrollbar-thumb": "rgba(88, 110, 117, 0.3)",
    "scrollbar-thumb-hover": "rgba(88, 110, 117, 0.45)",
    "scrollbar-thumb-thin": "rgba(88, 110, 117, 0.2)",
    "scrollbar-thumb-thin-hover": "rgba(88, 110, 117, 0.35)",
  },
  dark: {
    background: "#002b36",
    "app-chrome-background": "#002b36",
    foreground: "#93a1a1",
    card: "#073642",
    "card-foreground": "#93a1a1",
    popover: "#073642",
    "popover-foreground": "#93a1a1",
    primary: "#268bd2",
    "primary-foreground": "#002b36",
    secondary: "#073642",
    "secondary-foreground": "#93a1a1",
    muted: "#073642",
    "muted-foreground": "#657b83",
    accent: "#073642",
    "accent-foreground": "#eee8d5",
    destructive: "#dc322f",
    "destructive-foreground": "#fdf6e3",
    border: "rgba(147, 161, 161, 0.14)",
    input: "rgba(147, 161, 161, 0.18)",
    ring: "#268bd2",
    info: "#268bd2",
    "info-foreground": "#2aa198",
    success: "#859900",
    "success-foreground": "#859900",
    warning: "#b58900",
    "warning-foreground": "#b58900",
    "scrollbar-thumb": "rgba(147, 161, 161, 0.18)",
    "scrollbar-thumb-hover": "rgba(147, 161, 161, 0.32)",
    "scrollbar-thumb-thin": "rgba(147, 161, 161, 0.12)",
    "scrollbar-thumb-thin-hover": "rgba(147, 161, 161, 0.24)",
  },
};

const NORD: ThemeDefinition = {
  id: "nord",
  name: "Nord",
  description: "Cool arctic blues inspired by the Nord palette by Arctic Ice Studio.",
  builtIn: true,
  dark: {
    background: "#2e3440",
    "app-chrome-background": "#2e3440",
    foreground: "#d8dee9",
    card: "#3b4252",
    "card-foreground": "#e5e9f0",
    popover: "#3b4252",
    "popover-foreground": "#e5e9f0",
    primary: "#88c0d0",
    "primary-foreground": "#2e3440",
    secondary: "#434c5e",
    "secondary-foreground": "#e5e9f0",
    muted: "#3b4252",
    "muted-foreground": "#7b8794",
    accent: "#434c5e",
    "accent-foreground": "#eceff4",
    destructive: "#bf616a",
    "destructive-foreground": "#eceff4",
    border: "rgba(216, 222, 233, 0.1)",
    input: "rgba(216, 222, 233, 0.14)",
    ring: "#88c0d0",
    info: "#81a1c1",
    "info-foreground": "#8fbcbb",
    success: "#a3be8c",
    "success-foreground": "#a3be8c",
    warning: "#ebcb8b",
    "warning-foreground": "#ebcb8b",
    "scrollbar-thumb": "rgba(216, 222, 233, 0.16)",
    "scrollbar-thumb-hover": "rgba(216, 222, 233, 0.28)",
    "scrollbar-thumb-thin": "rgba(216, 222, 233, 0.12)",
    "scrollbar-thumb-thin-hover": "rgba(216, 222, 233, 0.22)",
  },
};

const HIGH_CONTRAST: ThemeDefinition = {
  id: "high-contrast",
  name: "High Contrast",
  description: "Maximum-contrast monochrome with yellow accents for accessibility.",
  builtIn: true,
  light: {
    background: "#ffffff",
    "app-chrome-background": "#ffffff",
    foreground: "#000000",
    card: "#ffffff",
    "card-foreground": "#000000",
    popover: "#ffffff",
    "popover-foreground": "#000000",
    primary: "#0000ee",
    "primary-foreground": "#ffffff",
    secondary: "#f5f5f5",
    "secondary-foreground": "#000000",
    muted: "#f0f0f0",
    "muted-foreground": "#1a1a1a",
    accent: "#ffeb3b",
    "accent-foreground": "#000000",
    destructive: "#cc0000",
    "destructive-foreground": "#ffffff",
    border: "#000000",
    input: "#000000",
    ring: "#0000ee",
    info: "#0000ee",
    "info-foreground": "#0000aa",
    success: "#006400",
    "success-foreground": "#003200",
    warning: "#996600",
    "warning-foreground": "#664400",
    "scrollbar-thumb": "rgba(0, 0, 0, 0.55)",
    "scrollbar-thumb-hover": "rgba(0, 0, 0, 0.8)",
    "scrollbar-thumb-thin": "rgba(0, 0, 0, 0.45)",
    "scrollbar-thumb-thin-hover": "rgba(0, 0, 0, 0.7)",
    "noise-opacity": "0",
  },
  dark: {
    background: "#000000",
    "app-chrome-background": "#000000",
    foreground: "#ffffff",
    card: "#000000",
    "card-foreground": "#ffffff",
    popover: "#000000",
    "popover-foreground": "#ffffff",
    primary: "#ffff00",
    "primary-foreground": "#000000",
    secondary: "#1a1a1a",
    "secondary-foreground": "#ffffff",
    muted: "#0d0d0d",
    "muted-foreground": "#e6e6e6",
    accent: "#ffff00",
    "accent-foreground": "#000000",
    destructive: "#ff5555",
    "destructive-foreground": "#000000",
    border: "#ffffff",
    input: "#ffffff",
    ring: "#ffff00",
    info: "#5fd7ff",
    "info-foreground": "#5fd7ff",
    success: "#5fff5f",
    "success-foreground": "#5fff5f",
    warning: "#ffff5f",
    "warning-foreground": "#ffff5f",
    "scrollbar-thumb": "rgba(255, 255, 255, 0.55)",
    "scrollbar-thumb-hover": "rgba(255, 255, 255, 0.85)",
    "scrollbar-thumb-thin": "rgba(255, 255, 255, 0.4)",
    "scrollbar-thumb-thin-hover": "rgba(255, 255, 255, 0.7)",
    "noise-opacity": "0",
  },
};

export const BUILT_IN_THEMES: readonly ThemeDefinition[] = [
  DEFAULT_THEME,
  SOLARIZED_DARK,
  NORD,
  HIGH_CONTRAST,
];
